### ISSUE TITLE
--attn_type 2 throwing size mismatch error with pytorch code ( -attn_type 0/1/3 work fine)

### ISSUE THREAD

**Issue by vikasverma1077** [kimiyoung/transformer-xl#74]
Hi , I am trying to use --attn_type 2 with enwik8 dataset. Here is the exact command I am using : python train.py         --cuda         --data ../data/enwik8/         --dataset enwik8         --n_layer 12         --d_model 512         --n_head 8         --d_head 64         --d_inner 2048         --dropout 0.1         --dropatt 0.0         --optim adam         --lr 0.00025         --warmup_step 0         --max_step 400000         --tgt_len 512         --mem_len 512         --eval_tgt_len 128  --batch_size 12 --attn_type 2

It throws the following error: 
Traceback (most recent call last):
  File "train.py", line 539, in <module>
    train()
  File "train.py", line 445, in train
    ret = para_model(data, target, *mems)
  File "/network/home/vermavik/miniconda2/envs/al/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/network/home/vermavik/github/transformer-xl/pytorch/mem_transformer.py", line 745, in forward
    hidden, new_mems = self._forward(data, mems=mems)
  File "/network/home/vermavik/github/transformer-xl/pytorch/mem_transformer.py", line 706, in _forward
    mems_i += pos_emb[:mlen]
RuntimeError: The size of tensor a (0) must match the size of tensor b (512) at non-singleton dimension 2

**Comment by sunjhfighting** [comment]
Hello, may I ask how you solved this issue later? I would greatly appreciate it if you could reply to me.

**Comment by sunjhfighting** [comment]
> Hi , I am trying to use --attn_type 2 with enwik8 dataset. Here is the exact command I am using : python train.py --cuda --data ../data/enwik8/ --dataset enwik8 --n_layer 12 --d_model 512 --n_head 8 --d_head 64 --d_inner 2048 --dropout 0.1 --dropatt 0.0 --optim adam --lr 0.00025 --warmup_step 0 --max_step 400000 --tgt_len 512 --mem_len 512 --eval_tgt_len 128 --batch_size 12 --attn_type 2
> 
> It throws the following error: Traceback (most recent call last): File "train.py", line 539, in train() File "train.py", line 445, in train ret = para_model(data, target, *mems) File "/network/home/vermavik/miniconda2/envs/al/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in **call** result = self.forward(*input, **kwargs) File "/network/home/vermavik/github/transformer-xl/pytorch/mem_transformer.py", line 745, in forward hidden, new_mems = self._forward(data, mems=mems) File "/network/home/vermavik/github/transformer-xl/pytorch/mem_transformer.py", line 706, in _forward mems_i += pos_emb[:mlen] RuntimeError: The size of tensor a (0) must match the size of tensor b (512) at non-singleton dimension 2

Hello, may I ask how you solved this issue later? I would greatly appreciate it if you could reply to me.
