### ISSUE TITLE
Result of wt103_base

### ISSUE THREAD

**Issue by stylelohan** [kimiyoung/transformer-xl#99]
Hi, thank you for the open source.

After I finished running run_wt103_base.sh with 4 GPUs, my final result looked like this:

```
| Eval  50 at step   200000 | time: 3815.87s | valid loss  3.15 | valid ppl    23.290
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
End of training
============================================================================
| End of training | test loss  3.19 | test ppl    24.248
============================================================================
Evaluating with bsz 10 tgt_len 64 ext_len 0 mem_len 640 clamp_len 400
Time : 34.78s, 90.57ms/segment
============================================================================
| test loss  3.16 | test ppl    23.683 
============================================================================
```

Would you mind tell me which test ppl is the correct one? (The one reported in your paper&github) If 24.248 is the correct test ppl, I wonder why it cannot achieve 24.03 as you said in your github (since every random seed has been fixed).

By the way, will the result be the same if I use only 2 GPUs to train wt103 base ?
Thanks a lot!

**Comment by CapGOGO** [comment]
Hi. Can you tell how much time did it take to train the model on wt103 with 4 GPUs???

**Comment by stylelohan** [comment]
> Hi. Can you tell how much time did it take to train the model on wt103 with 4 GPUs???

I have trained for about 2.5 days on 4 GPUs (1080 Ti).

**Comment by CapGOGO** [comment]
Thank you !

**Comment by AndreaLK3** [comment]
A question: when I try to execute run_wt103_base.sh, I get an import error:
`Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from data_utils import get_lm_corpus
  File "/home/andrealk3/ALMA_PhD/transformer-xl/pytorch/data_utils.py", line 8, in <module>
    from utils.vocabulary import Vocab
**ImportError: No module named utils.vocabulary**`

How have you managed to avoid this import error?

(this is almost worth opening a new issue)
